### ISSUE TITLE
Design von Beiträgen in einer Seite (Block: Neuste Beiträge)

### ISSUE THREAD

**Issue by annettzobel** [openeduhub/wirlernenonline-theme#1]
Das Element Neuste Beiträge hat noch kein Design-Händchen abbekommen.
(Überschrift, Textausschnitt, Bilddarstellung, Anordnung Bild - Text)

Die Einbindung sollte so möglich sein, dass eine Eintragsliste wie ein Teil des Seitenfließtext wirkt.
Dazu sollte der Text links und rechts bündig zu den anderen Texten erscheinen

Im Editor sieht es so aus (da sollte das Bild linksbündig zu über-/untergeordneten Seitentext sein)
![image](https://user-images.githubusercontent.com/29773981/79731312-6536ad00-82f2-11ea-9c2e-83e004e0b478.png)

So sieht es in der Seite aus (Die Bilder sind bei dieser Einstellung nicht linksbündig. Auch andere Bildanordnungseinstellungen führen zu nicht ganz so schönen Ansichten ;-) )
![image](https://user-images.githubusercontent.com/29773981/79731495-a202a400-82f2-11ea-8ff2-ecd6e43ba78d.png)

Dieses Issue sollte vielleicht im Kontext des gesamten Designs der Seite bearbeitet werden, die derzeit so aussieht:
![image](https://user-images.githubusercontent.com/29773981/79731834-205f4600-82f3-11ea-832a-7a77c1ff8ce4.png)

Wir werden wahrscheinlich folgende Elemente auf der Seite brauchen:

1. Titel (H1) - Intro mit Ansprache, ein Motivbild, damit man weiß auf welcher Seite man ist
![image](https://user-images.githubusercontent.com/29773981/79873935-0e130400-83e8-11ea-8270-ff82b115e8c2.png)

2. Einen Zugang zur Suche (entweder so wie jetzt, oder gleich einen Suchschlitz. Dann könnte man anzeigen, wie viele Materialien für Lehrende da sind, wie viele in den letzten N Tagen hinzukamen (also Suchzugang zeigen "wir arbeiten für euch - fleißig"

![image](https://user-images.githubusercontent.com/29773981/79874161-4ca8be80-83e8-11ea-91a0-783d5578d758.png)

3. Einen flexibel gestaltbaren Bereich, wo die Redaktion die besten / wichtigsten Hilfestellungen verlinkt. Jeder Link sollte wie eine Box / Infoeinheit dargestellt werden. Es gibt unterschiedliche Arten von Infos (wir wissen noch nicht welche und wie viele). 
Daher wäre es schön, ein flexibles Boxen-Design zu haben, das ein- und zwei ggf. 3-spaltig funktioniert, Inhalte z.B.

3a. Text-Tipp der Redaktion:   nur Text der direkt in der Seite steht und einen Tipp gibt "Starte einfach, nutze Werkzeuge, die du beherrscht, baue später aus, lorm ipsum" (vielleicht 3-5 Zeilen in einer Spalte), eventuuuueeeel ein motivbild für den Tipp

3b. Tipp der Redaktion als Link zu einer ausführlicheren FAQ-Seite

3b. Zugang zu einem externen Kurs. Box beinhaltet einen 
Titel des Angebots auf das gelinkt wird, 
ggf. etwas Erklärungstext, 
ggf. ein Thumbnail (Logo des Kursanbieters)
ein grauer hinweistext zu sonstig wissenswertem (z.B. nur 1 Tag kostenfrei)

3c. Medium / Mediengalerie / Slider 
eine visuelle Fläche, die mehrere Seiten haben kann. Jede Seite kann ein Bild, ein Video (auch youtube) , ... sein
![image](https://user-images.githubusercontent.com/29773981/79875202-9b0a8d00-83e9-11ea-8a59-f4a8d23488a3.png)

**Comment by webendbananas** [comment]
@annettzobel Ich schaue mir das an. Bis Morgen mittag werden ich das bearbeiten. Hinweis: Ich habe mal alle Blöcke, die noch nicht getestet sind deaktiviert. D.h. die kann man gar nicht benutzen.

**Comment by webendbananas** [comment]
@annettzobel Ich habe mal die "Latest Posts" neu gemacht. Sieht jetzt so aus…
![Bildschirmfoto vom 2020-04-22 um 09 58 55](https://user-images.githubusercontent.com/3490426/79956065-ebccc500-847f-11ea-83ac-849a937f518b.png)

**Comment by webendbananas** [comment]
Leider hatte ich die weitere Anmerkungen überlesen. Bitte für jede Aufgabe eine einzelnen issue anlegen. Melde mich später noch mal.

**Comment by lennarto14** [comment]
Layout der neusten (Blog-)Beiträge hatte Ingo ja schon umgesetzt, die feauture requests habe ich aufgesplittet
