### ISSUE TITLE
Newsletter Anmeldelink

### ISSUE THREAD

**Issue by annettzobel** [openeduhub/wirlernenonline-theme#12]
Können wir die Anmeldung zum Newsletter auf einer extra Seite mit etwas Prosa haben?

Haben in der Mailbox Anfragen zum Mitmachen...
und würden gern vorerst in unseren Antworten einen Link auf die Newsletteranmeldung verlinken.

Bitte bitte...

**Comment by domtheis** [comment]
Seite erstellt: https://wirlernenonline.de/newsletter/
