### ISSUE TITLE
verschiedene Schriftarten

### ISSUE THREAD

**Issue by Basti-OEH** [openeduhub/wirlernenonline-theme#14]
Mir ist aufgefallen, dass wir unterschiedliche Schriftarten (mit Serifen und ohne Serifen)  auf der Seite haben (siehe Screenshot). Ist das gewollt? 
![grafik](https://user-images.githubusercontent.com/64004102/79959321-46682000-8484-11ea-9787-b771053a6169.png)

**Comment by webendbananas** [comment]
Wir haben einen neuen, nicht so schweren Font eingesetzt. bitte mal Cache des Browsers löschen, dann sollte alles wieder gut sein.

**Comment by Basti-OEH** [comment]
alles klar, hat sich erledigt  :-D
