### ISSUE TITLE
Spalten-Überschriften: Typo wird abgeschnitten

### ISSUE THREAD

**Issue by AlxMllrWMDE** [openeduhub/wirlernenonline-theme#21]
Bei viel Text in der Überschrift bei Spalten (z.B. im Blog, zweiter Eintrag von links: https://wirlernenonline.de/neuigkeiten/) wird in meiner Darstellung 1-2 Zeichen abgeschnitten. Hier das "?" hinter Lernumgebung. Das passiert auch anderenorts bei z.B. Suchergebnisliste.

**Comment by ernst-metaventis** [comment]
fixed
