### ISSUE TITLE
Aussagekräftigeres Nutzerfeedback fürs "Hinzufügen"

### ISSUE THREAD

**Issue by lennarto14** [openeduhub/wirlernenonline-theme#22]
"Deine Quelle wurde angelegt" kann den Eindruck vermitteln, dass die Quelle direkt auftauchen sollte auf der Seite (was ja nicht der Fall) - hier wäre es vorteilhaft den Nutzern genauer zu informieren, welche Vorgänge in Gang gesetzt wurden / was jetzt mit der Quelle passiert

<img width="617" alt="Bildschirmfoto 2020-04-27 um 10 59 46" src="https://user-images.githubusercontent.com/59307412/80354694-5f534580-8877-11ea-8abb-fff979fdeadb.png">

**Comment by ernst-metaventis** [comment]
Der Text kann geändert werden. Gibt es da schon Vorschläge?

Ansonsten würde ich das erst einmal auf 'Deine Quelle wurde gespeichert und wird jetzt von einem Redakteur zur Veröffentlichung geprüft.' ändern.

**Comment by annettzobel** [comment]
„Vielen Dank. Deine Quelle wurde gespeichert. Sie wird vor Veröffentlichung von der Redaktion geprüft.“
(bitte generell nicht die männliche Schreibweise nutzen ;-*)

Darüberhinaus wäre schön:
Könnte die Nutzer*in nach dem Absenden ihres Vorschlags auf der Quellen-Status-Seite landen. Die gelbe „Vielen Dank...“ Meldung ganz oben eingeblendet.
Darunter in der Tabelle aller Quellen findet die Nutzer*in dann 
ihren Quellenvorschlag ganz oben (idealerweise hervorgehoben)
Der Status der 1. Spalte könnte sein „...“ - diese 3 Punkte könnten mit einem Overlay verlinkt sein, welches sagt:
Die Redaktion prüft seit
N Tagen
Eingangsdatum: 02.05.2020

**Comment by ernst-metaventis** [comment]
Die Erfolgsmeldung wurde angepasst und es gibt jetzt einen Button, der zur Quellen-Übersicht führt.
