### ISSUE TITLE
Mobile Suche auf Startseite eher umbrechen

### ISSUE THREAD

**Issue by annettzobel** [openeduhub/wirlernenonline-theme#23]
Bitte brecht nen bissel eher um:
![image](https://user-images.githubusercontent.com/29773981/80817255-652b8c80-8bd1-11ea-833e-4a68fe12d3fb.png)

bitte gebt uns einen "Suche-wieder-ausblenden X"
![image](https://user-images.githubusercontent.com/29773981/80817322-81c7c480-8bd1-11ea-8ee2-ccfd050badf7.png)

**Comment by ernst-metaventis** [comment]
added close-button and improved mobile-view
