### ISSUE TITLE
Content-Problem-Melden Fomular verbessern

### ISSUE THREAD

**Issue by annettzobel** [openeduhub/wirlernenonline-theme#26]
1. Wunsch
nach dem Formularabsenden, bleibt man im Formular und könnte noch ein Problem zum gleichen Content absenden. Das macht wenig Sinn.
Man sollte dahin zurück kommen, wo man her kam.
z.B. Tab schließen?

2. Wunsch
bitte aus den Radiobuttons (single choice) Checkboxen (Multiple choise) machen. Bei meinem 1. Nutzungsfall gab es 2 Probleme am Content

3. Wunsch
müssen wir wirklich Namen und Mailadresse als Pflichtfeld machen. Bei der Wikipedia kann jeder anonym ändern, - Fehler melden sollte doch auch anonym gehen.

![image](https://user-images.githubusercontent.com/29773981/80911593-8e662d00-8d37-11ea-9054-ff1cf0b37b57.jpeg)

![image](https://user-images.githubusercontent.com/29773981/80911581-6d054100-8d37-11ea-865b-755f019da5e3.png)

**Comment by christopher-l** [comment]
>     1. Wunsch
>        nach dem Formularabsenden, bleibt man im Formular und könnte noch ein Problem zum gleichen Content absenden. Das macht wenig Sinn.
>        Man sollte dahin zurück kommen, wo man her kam.
>        z.B. Tab schließen?

Etwas schwierig: Wenn man einfach den Tab schließt, weiß der Nutzer nicht, ob die Nachricht wirklich gesendet wurde. Ein Dialog, der dann den Tab schließt wirkt auch etwas komisch. Theoretisch könnte man von der Suche auf das Problemformular umleiten und dann zurück, wenn die Nachricht gesendet wurde, aber wahrscheinlich ist es praktischer für den Nutzer, beim Schreiben der Nachricht den Tab mit dem Inhalt weiterhin verfügbar zu haben.

> 
>     2. Wunsch
>        bitte aus den Radiobuttons (single choice) Checkboxen (Multiple choise) machen. Bei meinem 1. Nutzungsfall gab es 2 Probleme am Content

Geändert.

>     3. Wunsch
>        müssen wir wirklich Namen und Mailadresse als Pflichtfeld machen. Bei der Wikipedia kann jeder anonym ändern, - Fehler melden sollte doch auch anonym gehen.

Geändert -- Angabe ist jetzt freiwillig.

**Comment by christopher-l** [comment]
Schließe wegen Inaktivität. Wenn Probleme bestehen, bitte neu öffnen.
