### ISSUE TITLE
Kontaktformular Button style / Error indication

### ISSUE THREAD

**Issue by lennarto14** [openeduhub/wirlernenonline-theme#27]
Contact page , Send button can have same style like other buttons.Maybe change background color of rectangle  to red  indicate error message at bottom.

<img width="598" alt="Bildschirmfoto 2020-05-06 um 11 10 38" src="https://user-images.githubusercontent.com/59307412/81160341-3b37e880-8f8a-11ea-923a-26624a9cbdd7.png">

<img width="594" alt="Bildschirmfoto 2020-05-06 um 11 11 01" src="https://user-images.githubusercontent.com/59307412/81160381-47bc4100-8f8a-11ea-9e28-d47ee694370a.png">

**Comment by ernst-metaventis** [comment]
fixed
