### ISSUE TITLE
(wichtig!) Fächer auf Startseite

### ISSUE THREAD

**Issue by Basti-OEH** [openeduhub/wirlernenonline-theme#31]
Das Problem ist, dass der Fächerkanon auf der Startseite nicht der Schulform entspricht. 

Beispiel: Wenn ich auf "Grundschule" klicke, sollte nicht "Latein" als Auswahloption erscheinen. 

Für die **Grundschule** sollte es folgende Auswahl geben:

12002 : Darstellen & Gestalten
120 : Deutsch
20001 : Englisch
160 : Ethik
50001 : Hauswirtschaft
420 : Musik
520 : Religion
600 : Sport
50005 : Werken
28010 : Sachunterricht
060 : Kunst
380 : Mathe
560 : Sexualerziehung
44006 : Sonderpädagogik
660 : Verkehrserziehung

Für **Sekundarstufe I und Sekundarstufe II:** 
20003 : Alt-Griechisch
46014 : Astronomie
060 : Kunst
080 : Biologie
100 : Chemie
12002 : Darstellen & Gestalten
28002 : Deutsch als Zweitsprache/ DaZ
120 : Deutsch
20001 : Englisch
220 : Geographie
04006 : Ernährung und Hauswirtschaft
20090 : Esperanto
160 : Ethik
20002 : Französisch
240 : Geschichte
260 : Gesundheit
48005 : Gesellschaftskunde
50001 : Hauswirtschaft
720 : Allgemein/ Sonstiges
320 : Informatik
20004 : Italienisch
20005 : Latein
380 : Mathe
400 : Medienpädagogik
420 : Musik
niederdeutsch : Niederdeutsch
440 : Pädagogik
450 : Philosophie
460 : Physik
480 : Politik
510 : Psychologie
04013 : Recht
520 : Religion
20006 : Russisch
560 : Sexualerziehung
44006 : Sonderpädagogik
20009 : Sorbisch
44007 : Sozialkunde
20007 : Spanisch
600 : Sport
20008 : Türkisch
640 : Umweltgefährdung, Umweltschutz
680 : Weiterbildung
50005 : Werken
700 : Wirtschaftskunde

Für **Berufliche Bildung**:
04001 : Agrarwirtschaft
020 : Arbeitslehre
04014 : Arbeitssicherheit
04002 : Bautechnik
04003 : Drucktechnik
04005 : Elektrotechnik
04007 : Farbtechnik und Raumgestaltung
04009 : Holztechnik
04011 : Metalltechnik
04012 : Textiltechnik und Bekleidung
660 : Verkehrserziehung
20003 : Alt-Griechisch
46014 : Astronomie
060 : Kunst
080 : Biologie
100 : Chemie
12002 : Darstellen & Gestalten
28002 : Deutsch als Zweitsprache/ DaZ
120 : Deutsch
20001 : Englisch
220 : Geographie
04006 : Ernährung und Hauswirtschaft
20090 : Esperanto
160 : Ethik
20002 : Französisch
240 : Geschichte
260 : Gesundheit
48005 : Gesellschaftskunde
50001 : Hauswirtschaft
720 : Allgemein/ Sonstiges
320 : Informatik
20004 : Italienisch
20005 : Latein
380 : Mathe
400 : Medienpädagogik
420 : Musik
niederdeutsch : Niederdeutsch
440 : Pädagogik
450 : Philosophie
460 : Physik
480 : Politik
510 : Psychologie
04013 : Recht
520 : Religion
20006 : Russisch
560 : Sexualerziehung
44006 : Sonderpädagogik
20009 : Sorbisch
44007 : Sozialkunde
20007 : Spanisch
600 : Sport
20008 : Türkisch
640 : Umweltgefährdung, Umweltschutz
680 : Weiterbildung
50005 : Werken
700 : Wirtschaftskunde

**Comment by ernst-metaventis** [comment]
Aktuell werden die Fächer ja anhand der verfügbaren Materialien automatisch ausgewählt.
Davon wollen wir also wieder weg und nur die feste Auswahl an Fächern (sofern es Materialien gibt)?

**Comment by Basti-OEH** [comment]
nein, von der automatischen Auswahl wollen wir auf keinen Fall weg. Wir wollen nur verhindern, dass bei den Suchfeldern auf der Startseite Fächer für Bildungsstufen angezeigt werden, die es für diese Bildungsstufen gar nicht gibt.

Beispiel: der Nutzer ist verwirrt, wenn er auf "Grundschule" klickt und dort "Beurfliche Bildung" o.Ä. vor findet. 

![grafik](https://user-images.githubusercontent.com/64004102/81307039-774d7500-9080-11ea-975b-3fee583d7507.png)

**Comment by ernst-metaventis** [comment]
Die erlaubten Fächer können jetzt auf der Startseite eingestellt werden.
