### ISSUE TITLE
BUG - Startseitenfächer

### ISSUE THREAD

**Issue by Basti-OEH** [openeduhub/wirlernenonline-theme#32]
Mathe taucht in der Suche auf der Startseite nicht mehr auf - im WP-BackEnd wirds jedoch angezeigt. 
![grafik](https://user-images.githubusercontent.com/64004102/82062252-21a14a00-96ca-11ea-9bc8-b7634efe1ad7.png)

**Comment by ernst-metaventis** [comment]
Aktuell wird das noch über die deutschen Namen und nicht über unsere Metadaten-Id's abgeglichen und die waren leider unterschiedlich. Du muss die API bei der Suche noch mal angepasst werden.

Für Mathe ist es jetzt korrigiert. Sollten noch andere Fächer fehlen, sag Bescheid.
