### ISSUE TITLE
"Quelle/Tool hinzufügen"-Button auf Such-Seite WLO

### ISSUE THREAD

**Issue by Nele-B** [openeduhub/wirlernenonline-theme#33]
Es fehlt auf der [Suche-Übersichtsseite](https://suche.wirlernenonline.de/de/search?q=&pageIndex=0) von WirLernenOnline prominent platziert der Call-to-Action mit entsprechender Verlinkung zu den Formularen[ "Quelle hinzufügen" ](https://wirlernenonline.de/quelle-hinzufuegen/)beziehungsweise ["Tool hinzufügen"](https://wirlernenonline.de/tool-hinzufuegen/).

**Comment by christopher-l** [comment]
Gelöst. Siehe https://github.com/openeduhub/oeh-search-frontend/issues/5
