### ISSUE TITLE
Graue Boxen

### ISSUE THREAD

**Issue by webendbananas** [openeduhub/wirlernenonline-theme#8]
Hi,
Die würden sich wünschen, so graue Boxen in dieser 2spaltigkeit zu haben für diese Mini Absätze. 

https://wirlernenonline.de/lehrende/

@webendbananas

**Comment by annettzobel** [comment]
Ist hier mit drin, kann geschlossen / verschoben werden
https://github.com/openeduhub/wirlernenonline-theme/issues/1
